// <auto-generated />
using System;
using DiningPhilosophers.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DiningPhilosophers.Persistence.Migrations
{
    [DbContext(typeof(SimulationDbContext))]
    [Migration("20251222210447_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiningPhilosophers.Persistence.Entities.ForkStateEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ForkNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Owner")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("StepNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "TimestampUtc");

                    b.ToTable("ForkStateEvents");
                });

            modelBuilder.Entity("DiningPhilosophers.Persistence.Entities.PhilosopherStateEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CurrentAction")
                        .HasColumnType("text");

                    b.Property<bool?>("HasLeftFork")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasRightFork")
                        .HasColumnType("boolean");

                    b.Property<string>("PhilosopherName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("StepNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("StepsRemaining")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "TimestampUtc");

                    b.ToTable("PhilosopherStateEvents");
                });

            modelBuilder.Entity("DiningPhilosophers.Persistence.Entities.SimulationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("DiningPhilosophers.Persistence.Entities.ForkStateEvent", b =>
                {
                    b.HasOne("DiningPhilosophers.Persistence.Entities.SimulationRun", null)
                        .WithMany("ForkStateEvents")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiningPhilosophers.Persistence.Entities.PhilosopherStateEvent", b =>
                {
                    b.HasOne("DiningPhilosophers.Persistence.Entities.SimulationRun", null)
                        .WithMany("PhilosopherStateEvents")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiningPhilosophers.Persistence.Entities.SimulationRun", b =>
                {
                    b.Navigation("ForkStateEvents");

                    b.Navigation("PhilosopherStateEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
